### ISSUE TITLE
punc/scr/superlu/punc submodules superlu and vf2c headers don't get into build/fetk/include/punc

### ISSUE THREAD

**Issue by BJWiley233** [Electrostatics/apbs#196]
When I run cmake from apbs build directory with `-DENABLE_FETK=ON` the headers I need for punc do not get copied over from [punc/scr/superlu/punc](https://github.com/Electrostatics/FETK/tree/0fe0adb34b815a0866f1ed2d3886936f3bae9c69/punc/src/superlu/punc) (12 header files / 11 minus old_colamd.h) or [punc/scr/superlu/vf2c](https://github.com/Electrostatics/FETK/tree/0fe0adb34b815a0866f1ed2d3886936f3bae9c69/punc/src/vf2c/punc) (6 header files) and so mc fails because it depends on punc/vsuperlu.h.  I have superlu already compiled from their git repo because they have been actively updating over the past 5 years.  

Interestingly I can build fetk directly by itself from a build directory and all the headers from `amd`, `umfpack` and `superlu` get into the build directory include but still missing vf2c.h which is ironic because the other 5 headers from [punc/scr/superlu/vf2c](https://github.com/Electrostatics/FETK/tree/0fe0adb34b815a0866f1ed2d3886936f3bae9c69/punc/src/vf2c/punc are there and lib/libvf2c.a static still gets made? 

So from the apbs main directory I am not sure this in [externals/fetk/punc/CMakeLists.txt]()(https://github.com/Electrostatics/FETK/blob/main/punc/CMakeLists.txt) allows the punc specific headers to be included from both superlu and vf2c are working for installing their punc respective headers to the apbs build/fetk directory??

```
# vf2c library [done]
set(BUILD_VF2C ON)
...
# SuperLU library [done]
find_package( SuperLU )
if(NOT SuperLU_FOUND)
    set(BUILD_SUPERLU ON)
else()
    set(BUILD_SUPERLU OFF)
endif()
```

**Comment by BJWiley233** [comment]
ok so I know why vf2c.h is missing from the punc/vf2c module.  You are missing it in punc/src/vf2c/CMakeLists.txt line [21](https://github.com/Electrostatics/FETK/blob/0fe0adb34b815a0866f1ed2d3886936f3bae9c69/punc/src/vf2c/CMakeLists.txt#L21). 

It should read to include `punc/vf2c.h`:
```
add_build_items(
    TYPE EXTERNAL_HEADERS
    ITEMS punc/varpack.h
          punc/vblas.h
          punc/vcgcode.h
          punc/vlapack.h
          punc/vpmg.h
          punc/vf2c.h
)
```

**Comment by nsoblath** [comment]
Thanks for pointing out this problem, @BJWiley233.  FETK will be fixed shortly, and the build is significantly different than what's used as a submodule of APBS v3.0.  All of these changes will be addressed in the upcoming release of v3.3.0.

**Comment by BJWiley233** [comment]
Thanks @nsoblath.  I think my greatest hinderance of building the submodules, i.e. fetk, from the APBS CMakeLists.txt is that despite packages being found by the APBS CMakeLists.txt, this does not trickle down to fetk's CMakeList.txt and it will try to make some of the src's such as superlu and blas.  I added find_package superlu to just to double confirm this.

from main CMake call to APBS CMakeLists.txt
```
-- Found SuperLU: /usr/local/include (found version "5.0")`
-- Found BLAS: /usr/local/Cellar/openblas/0.3.19/lib/libopenblas.dylib
```

But still in the call to make for fetk you will still see it trying to build:
```
Making all in blas
Making all in .
...
...
Making all in superlu
Making all in .
```

**Comment by nsoblath** [comment]
@BJWiley233 That's a really good point.  And this is something that's hopefully addressed in the new builds of APBS and FETK.  (if you're interested in seeing the changes that are being made, you can find the most recent changes in the branch `nsoblath/issue_163`, but please understand that it's not yet a production release.)

**Comment by BJWiley233** [comment]
Thanks @nsoblath.  I just tried compiling and still get the same `Undefined symbols for architecture x86_64` issue while linking `libPBAMLib.dylib`. I think there is an issue with respect to using the apbs `generic/*.h` header files in the submodules before apbs even gets compiled or they are not linking correctly.  For instance [PBAMWrap.h](https://github.com/Electrostatics/pb_solvers/blob/db4fc6e90e3d94de7ca91d00a32743b5f132ae6e/pb_wrap/src/PBAMWrap.h) in the PBAM submodule includes [generic/valist.h](https://github.com/Electrostatics/apbs/blob/master/src/generic/valist.h) from apbs.  Feel like it doesn't know where to get this header from if it's not included in cmake files?

```
[  6%] Linking CXX shared library libPBAMLib.dylib
cd /Users/brian/tools/apbs/build/_deps/pb_s_am-build/pbam/src && /usr/local/Cellar/cmake/3.22.1/bin/cmake -E cmake_link_script CMakeFiles/PBAMLib.dir/link.txt --verbose=2
+ cd /Users/brian/tools/apbs/build/_deps/pb_s_am-build/pbam/src
+ /usr/local/Cellar/cmake/3.22.1/bin/cmake -E cmake_link_script CMakeFiles/PBAMLib.dir/link.txt --verbose=2
/usr/bin/g++ -I/usr/local/Cellar/libomp/13.0.0/include -L/usr/local/Cellar/libomp/13.0.0/lib -lomp -I/Users/brian/tools/apbs/src -Wall -Wpedantic -fpermissive -fPIC -std=c++11 -funroll-loops -Xclang -fopenmp -O2 -g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX-SDKs/MacOSX11.3.sdk -mmacosx-version-min=11.3 -dynamiclib -Wl,-headerpad_max_install_names -L/Library/Developer/CommandLineTools/SDKs/MacOSX-SDKs/MacOSX11.3.sdk/usr/lib -o libPBAMLib.dylib -install_name @rpath/libPBAMLib.dylib CMakeFiles/PBAMLib.dir/__/__/pb_wrap/src/PBAMWrap.cpp.o CMakeFiles/PBAMLib.dir/ASolver.cpp.o CMakeFiles/PBAMLib.dir/__/__/pb_shared/src/BaseBD.cpp.o CMakeFiles/PBAMLib.dir/__/__/pb_shared/src/BaseElectro.cpp.o CMakeFiles/PBAMLib.dir/__/__/pb_shared/src/BaseSys.cpp.o CMakeFiles/PBAMLib.dir/BDAM.cpp.o CMakeFiles/PBAMLib.dir/__/__/pb_shared/src/BesselCalc.cpp.o CMakeFiles/PBAMLib.dir/__/__/pb_shared/src/Constants.cpp.o CMakeFiles/PBAMLib.dir/ElectrostaticsAM.cpp.o CMakeFiles/PBAMLib.dir/PhysCalcAM.cpp.o CMakeFiles/PBAMLib.dir/PBAM.cpp.o CMakeFiles/PBAMLib.dir/__/__/pb_shared/src/ReExpCalc.cpp.o CMakeFiles/PBAMLib.dir/__/__/pb_shared/src/setup.cpp.o CMakeFiles/PBAMLib.dir/__/__/pb_shared/src/SHCalc.cpp.o CMakeFiles/PBAMLib.dir/SystemAM.cpp.o   -L/Users/brian/tools/apbs/build/_deps/fetk-src/lib 
Undefined symbols for architecture x86_64:
  "_Valist_getAtom", referenced from:
      _runPBAMWrapAPBS in PBAMWrap.cpp.o
  "_Valist_getNumberAtoms", referenced from:
      _runPBAMWrapAPBS in PBAMWrap.cpp.o
  "_Vatom_getCharge", referenced from:
      _runPBAMWrapAPBS in PBAMWrap.cpp.o
  "_Vatom_getPosition", referenced from:
      _runPBAMWrapAPBS in PBAMWrap.cpp.o
  "_Vatom_getRadius", referenced from:
      _runPBAMWrapAPBS in PBAMWrap.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nsoblath** [comment]
@BJWiley233 You're right about that being a problem too.  There were at least two places where APBS was using an external package both as a dependency of and dependent on APBS. These have been resolved in the version being prepared for the v3.3.0 release.

**Comment by BJWiley233** [comment]
Sounds good.  Looks like @intendo fixed similar stuff in @106
