### ISSUE TITLE
Get pybind11 to work in Appveyor and Github Actions

### ISSUE THREAD

**Issue by intendo** [Electrostatics/apbs#75]
The Appveyor file (https://github.com/Electrostatics/apbs/blob/master/appveyor.yml) and Github Actions file (https://github.com/Electrostatics/apbs/blob/master/.github/workflows/build.yml) need to be fixed so that pybind11 doesn't crash the builds.

**Comment by ashermancinelli** [comment]
@intendo I believe I fixed this (it's passing the CI builds), but can I get your confirmation before closing?

**Comment by intendo** [comment]
The Github Actions are working but Appveyor is still failing.

**Comment by ashermancinelli** [comment]
Appveyor appears to be passing for master now - is this resolved?

**Comment by intendo** [comment]
The only reason Appveyor is working is that it has Python and Shared Libraries turned off.
If we want to have Python via pybind11, we would want to turn Python and Shared Libraries on in Appveyor builds.
